### ISSUE TITLE
Byproduct utilization

### ISSUE THREAD

**Issue by joshbrowning2358** [SWS-Methodology/faoswsFeed#19]
At times, a process will create multiple products at one time, and the most commonly used example of this is the bran and germ produced during the creation of wheat flour.  The food module will impute food of flour, and after accounting for trade of flour we can determine how much wheat is being allocated for flour production.  This quantity is then the amount of wheat allocated to bran production as well, and this creates the bran needed for the feed module.  This approach applies to many of the oils, cereals, fruits, etc.

This isn't necessarily a task that the feed module should perform, but it's unclear to me of the best place to do this.  It must be done after the food module and before completely running the feed module, so it seems reasonable to do this immediately before the main processing of the feed module.  Maybe it would make the most sense to construct this as a separate module outside the main feed module...

An additional problem is that the identification of these by-products is not provided anywhere in the database (or at least, as far as I can tell).  I believe the information is contained in the image commodity trees here:
https://github.com/SWS-Methodology/faoswsStandardization/blob/master/documentation/technical_conversion_factor.pdf
and that we may be able to extract the information from the annexes:
https://github.com/SWS-Methodology/faoswsStandardization/blob/master/documentation/flexible_aggregation_of_FAO_supply_utilization_account_annexes_part2.pdf
In particular, annex 1 seems to have the information we need.  However, understanding why wheat can be processed into flour/bran/germ or just flour/bran is something we'll need to investigate.

**Comment by sebastian-c** [comment]
I think this is out of the scope of the feed module. It looks to me a like a balancing issue, The main reason I think that it should _not_ be in the Feed module is that it's useful information in itself. It's information that should be published. 

But you're right, it seems to be in a limbo after food (to get flour allocation of wheat) and before standardisation.

**Comment by joshbrowning2358** [comment]
Yeah, you're right, it's outside the scope of the feed module.  I'm not sure where we should put a module like this, though, or where we should incorporate it in the workflow.  Feel free to move this issue to a different repository if you think it'd be more relevant there...

**Comment by BDalheimer** [comment]
Can't we have it in the standardization module? The task it should perform belongs to it. Given that we need to run standardization as the last module though, we could have it as a preliminary standardization function which is put between food and feed in the sequence.

**Comment by joshbrowning2358** [comment]
Hmm...  Yeah, we could create an additional module within the standardization repository that does this synchronization, but we'll have to be careful about the sequence that we run the modules in.  The feed module should only be ran after this module, and we should create some way of ensuring that it has been completed.  Should I migrate this issue to faoswsStandardization?  Or do you guys have any other thoughts on this topic?

**Comment by joshbrowning2358** [comment]
Moving here:
https://github.com/SWS-Methodology/faoswsStandardization/issues/4
