### ISSUE TITLE
China zero Feed Demand

### ISSUE THREAD

**Issue by BDalheimer** [SWS-Methodology/faoswsFeed#2]
Currently, China (M49 code 1248) results zero feed demand. As the calculation involves data using different country codes, such as fao, M49, worldbank or even none (figis), we need to check whether the code conversions are carried out appropriately

**Comment by BDalheimer** [comment]
All the "minor chinas", namely hong kong, macao and taiwan are fine. However, there is nothing generated for either 1248 or 156, which are the codes for china, mainland. In the sws, it looks like all data for china is under 1248. They also have all other elements necessary for demand calculation. For aquaculture, the `countrycode` function assigned 156 to China, and not 1248, which leads to exclusion of it. I might have to hardcode this one. I think for the wdi import `countrycode` is used which might mess things up there as well leading to zero demand in china

**Comment by sebastian-c** [comment]
There's been a recent fix in the database regarding the code for China, so we might reopen this.
