### ISSUE TITLE
Labour Productivity imputation

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsFeed#21]
There are missing values in the labour productivity data and these need to be filled. These fit well into our current scripts to develop `wdi`.

The draft work plan is:
1. Calculate mean trendlines for each country World Bank income group _excluding_ the Small Island Developing States
2. Where there does not exist any data for that country, copy the income group trendline
3. Where there does exist data, scale the trendline by the mean of the existing data and apply the trendline values to missing data

**Comment by BDalheimer** [comment]
Here's the link to the WB income classification scheme. There csv is at the bottom.
http://data.worldbank.org/about/country-and-lending-groups

**Comment by sebastian-c** [comment]
This was completed in 1b4d10791c76bd7b09eeca2b4dd799a073b13ebd

**Comment by sebastian-c** [comment]
Egypt has been shown to be problematic in regards to Land data (it doesn't have any). This link has some good information: http://www.fao.org/ag/AGP/AGPC/doc/Counprof/Egypt/Egypt.html#pasture

**Comment by sebastian-c** [comment]
The previous comment refers to #26
