### ISSUE TITLE
If a country has no animal stocks, it will not appear in the results

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsFeed#3]
At the moment if a country has no animals and only fish, if will will not appear at all.

**Comment by BDalheimer** [comment]
Here's how livestock demand and aquaculture demand are currently brought together:

feedDemandData = merge(livestockDemand, aquaDemand, 
                       by = c("geographicAreaM49", "timePointYears"),
                       all.x = T)

can't this issue be resolved through 

feedDemandData = merge(livestockDemand, aquaDemand, 
                       by = c("geographicAreaM49", "timePointYears"),
                       **all = T**)

**Comment by sebastian-c** [comment]
That would add all the countries in aquaDemand to the request, including the ones the user didn't ask for. The problem is further up - I think there might be an option to return unmatched queries in GetData, however. I'll look into it.

**Comment by BDalheimer** [comment]
Maybe I've not programmed it appropriately - but shouldn't the aquaDemand function only grab the countries of the request?
