### ISSUE TITLE
Which flags are official?

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsFeed#5]
At the moment, we're using the `flagObservationStatus` variable for flags. Does this assumption hold for trade flags or are they still under the old flag system? It's difficult to tell as they all have the same value.

**Comment by BDalheimer** [comment]
Empty flag means official data, but I don't know if that holds for trade data as well. In any case, for the feed module, we only need the flags of feed, which are not part of the trade data. Technically, for any new year the model is run, there should _only_ be official data as any estimates are created by the model.

**Comment by sebastian-c** [comment]
We've solved the flag issue. All official feed keep their flag. All allocated feed gets (E, e), All feed-only feed gets (E,b).

**Comment by sebastian-c** [comment]
These are imputed values, so they've been assigned I, not E.
